### ISSUE TITLE
malloc issue in spglib 1.9

### ISSUE THREAD

**Issue by shyuep** [atztogo/spglib#9] opened 2016-04-06 15:46 UTC
There seems to be a malloc issue in 1.9 that is not present in 1.7.4. This arose when we tried to do symmetry analysis using a file with tricky symmetry. See commit in pymatgen https://github.com/materialsproject/pymatgen/commit/6ca6f79d61bb07bddbea33fa954d42f6a983bfb5 by @wmdrichards. The POSCAR file is available in the pymatgen repo under test_files/POSCAR.tricky.

**Comment by atztogo** [comment] 2016-04-07 04:16
I tested spglib 1.9.1 (I think no difference from 1.9.0) using POSCAR.tricky_symmetry https://github.com/materialsproject/pymatgen/blob/6ca6f79d61bb07bddbea33fa954d42f6a983bfb5/test_files/POSCAR.tricky_symmetry, but I couldn't reproduce the problem. But memory allocation problem is naive issue and can depend on systems. I did the test on Mac El Capitan and Ubuntu 14.04.
One question from me is: Have you updated _spglib.c, too?

The script I used for my test is:

from phonopy.interface.vasp import read_vasp # Read POSCAR and return Atoms class object
import spglib
cell = read_vasp("POSCAR.tricky_symmetry.txt")
dataset = spglib.get_symmetry_dataset(cell, symprec=1e-5)
print(dataset)

**Comment by shyuep** [comment] 2016-04-07 13:59
I did update _spglib.c and recompiled. But I think the symprec used was 1e-2. Not sure if that made a difference?

**Comment by shyuep** [comment] 2016-04-07 13:59
@wmdrichards Can you comment since you are the one who found the problem?

**Comment by wmdrichards** [comment] 2016-04-12 15:11
Yes, it seems to be a problem with higher (looser) symprec

**Comment by atztogo** [comment] 2016-04-13 01:26
I need more information, otherwise I will close this issue since I have no idea how to do.

**Comment by shyuep** [comment] 2016-04-13 02:57
I think what Will is saying is that if you site the site tolerance in spglib to a larger number, e.g., 0.01, you get the malloc error.

**Comment by atztogo** [comment] 2016-04-13 03:05
Of course I did it and no problem was found. Will's comment was not clear enough, even the sentence starts with "it seems". I need a test script that both of us can share to make it more clear. On the spglib side, I think I did what I could do.

**Comment by shyuep** [comment] 2016-04-13 03:23
I just validated this. spglib1.9.1 works fine. Think it was a spglib1.9.0 issue. I will close this issue.

**Comment by shyuep** [comment] 2016-04-14 22:38
I am reopening this issue now that I have a script that reproduces the error.

System: Ubuntu 64-bit
GCC version: 4.8.4
Setup: Virtualenv -> Install numpy 1.11.0 -> Install spglib 1.9.1 (python setup.py install. Tar.gz downloaded from sourceforge).

Test code:
```python
import spglib._spglib as spg
import json
import numpy as np

with open("POSCAR.tricky.json") as f:
    d = json.load(f)

lattice = np.array(d["lattice"], dtype='double', order='C')
positions = np.array(d["positions"], dtype='double', order='C')
numbers = np.array(d["numbers"], dtype='intc')

for tol in [0.001, 0.01, 0.1]:
    dataset = spg.dataset(lattice, positions, numbers, tol, 5)
    print dataset[2]
```

Input file: [POSCAR.tricky.json](https://www.dropbox.com/s/jw3d176eu50gfzl/POSCAR.tricky.json?dl=0)

Output obtained:
```
Cm
Cm
Segmentation fault (core dumped)
```

I can confirm that XCode gcc on Mac works just fine. See https://github.com/materialsproject/pymatgen/issues/334 for related info on other configurations that fail. 

I am not sure if you have access to a Ubuntu machine, but if you install a VM with the latest Ubuntu, you should be able to reproduce this fairly consistently.

**Comment by shyuep** [comment] 2016-04-14 22:52
Also, the problem arises only for higher tolerances, e.g., 0.1. When the tolerance is tighter, the seg fault does not occur. That should give some clue as to where there can be potential mem leaks?

**Comment by atztogo** [comment] 2016-04-15 10:24
I could reproduce this segfault. What was missing for me was running it with the large angle tolerance. I usually don't use it (negative value) and didn't check the code around carefully.
Using valgrind, I didn't see memory leaks, but I found invalid access to pointers. I tried to fix the code and now I don't see segfault. In addition, I implemented a better treatment of angle tolerance when it is too large. Finally Output obtained became
```
Cm
I4mm
I4/mmm
```

Thank you for your reopening this issue patiently.

**Comment by atztogo** [comment] 2016-04-15 10:24
The code is found at the commit 93965f55ff20f4217a611323e16be992220299df .

**Comment by shyuep** [comment] 2016-04-15 13:52
Thanks! Was the angle tolerance working previously?

**Comment by atztogo** [comment] 2016-04-15 14:07
I think most of the cases, it worked well. As an unusual case of POSCAR.tricky.json with large symprec and angle_tolerance, the order of point group became larger than 48 happened at https://github.com/atztogo/spglib/blob/v1.9.1/src/symmetry.c#L732 , which is not crystallographically possible. In my tests, I could never raise this unusual case. The treatment after this happens was not well done and finally it caused segfault.

**Comment by shyuep** [comment] 2016-04-15 16:11
Thanks! I am closing this issue. Pls let me know when a new spglib has been released and I will integrate it into pymatgen!

**Closed** 2016-04-15 16:12 UTC
