### ISSUE TITLE
SPGLib not returning None instead of P1 spacegroup info

### ISSUE THREAD

**Issue by shyamd** [atztogo/spglib#59] opened 2018-04-18 20:52 UTC
Referencing an issue detected via pymatgen: https://github.com/materialsproject/pymatgen/issues/1113

Basically the following structure seems to yield None from spglib rather than some spacegroup info. Code to recreate:
```python
from pymatgen import Structure

s = {'@class': 'Structure',
 '@module': 'pymatgen.core.structure',
 'lattice': {'a': 2.899999975486379,
  'alpha': 108.04703882787179,
  'b': 2.899999975486379,
  'beta': 107.6337551894724,
  'c': 2.899999975486379,
  'gamma': 112.78479361412218,
  'matrix': [[-1.703614, 1.712067, 1.605156],
   [1.703614, -1.712067, 1.605156],
   [1.703614, 1.712067, -1.605156]],
  'volume': 18.727042432703485},
 'sites': [{'abc': [0.0, 0.0, 0.0],
   'label': 'Sn',
   'species': [{'element': 'Sn', 'occu': 1}],
   'xyz': [0.0, 0.0, 0.0]}]}

st = Structure.from_dict(s)
st.get_space_group_info()
```

Yields the following error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-fe0a28cf7159> in <module>()
      1 from pymatgen import Structure
----> 2 Structure.from_dict(struc["input"]["structure"]).get_space_group_info()[0]

/Users/shyamd/codes/pymatgen/pymatgen/core/structure.py in get_space_group_info(self, symprec, angle_tolerance)
    703         a = SpacegroupAnalyzer(self, symprec=symprec,
    704                                angle_tolerance=angle_tolerance)
--> 705         return a.get_space_group_symbol(), a.get_space_group_number()
    706 
    707     def matches(self, other, **kwargs):

/Users/shyamd/codes/pymatgen/pymatgen/symmetry/analyzer.py in get_space_group_symbol(self)
    136             (str): Spacegroup symbol for structure.
    137         """
--> 138         return self._space_group_data["international"]
    139 
    140     def get_space_group_number(self):

TypeError: 'NoneType' object is not subscriptable

```

_space_group_data seems to be set to None and is only set by the following line:
```
self._space_group_data = spglib.get_symmetry_dataset(
            self._cell, symprec=self._symprec, angle_tolerance=angle_tolerance)
```
https://github.com/materialsproject/pymatgen/blob/master/pymatgen/symmetry/analyzer.py#L99-L100

It appears that spglib,get_symmetry_dataset is returning None. All the parameters passed to it are valid.

**Comment by atztogo** [comment] 2018-04-18 23:15
I am not a user of pymatgen and I don't know how I can create correct crystal structure though I can guess. Can you give me an example by spglib script to avoid confusion? The crystal structure format is found here, https://atztogo.github.io/spglib/python-spglib.html#crystal-structure-cell .

In addition, how much `symprec` is used to raise it?

**Comment by atztogo** [comment] 2018-04-18 23:35
Helpful. Confirmed. Thank you very much.
symprec=0.01 is reasonable. In case too tight, no problem.
It seems the problem happens related to the angle_tolerance. I don't use this usually and not well tested. I will investigate it.

**Comment by atztogo** [comment] 2018-04-19 02:17
I think (at least I hope), I could fix it at 2f7e2260bd00534e1c4b5cc058bfbef92fa0fe51 . I merged it to the master branch. Thanks for your raising this issue.

**Comment by atztogo** [comment] 2018-07-03 13:56
Can I close this issue?

**Comment by shyamd** [comment] 2018-07-03 14:52
Yes.  Thanks for the fix!

**Closed** 2018-07-16 23:40 UTC

**Comment by jrneilson** [comment] 2022-07-15 22:20
It looks like this issue (or at least a very similar one) has resurfaced when spglib was updated from version 1.16.3 to 1.16.5

**Comment by atztogo** [comment] 2022-07-15 23:16
@jrneilson, I could not confirm it using spglib installed via conda for m1-mac. Could you provide more detail?

**Comment by sgbaird** [comment] 2022-10-11 12:58
Here's a CIF file that should still produce the error. Note that this is a bad structure produced via a WIP generative model.
```cif
# generated using pymatgen
data_Li3TbScBe3ZnInGaSbArBNHeC
_symmetry_space_group_name_H-M   'P 1'
_cell_length_a   3.06768166
_cell_length_b   3.02260669
_cell_length_c   4.76862745
_cell_angle_alpha   30.44117647
_cell_angle_beta   32.17993080
_cell_angle_gamma   32.47058824
_symmetry_Int_Tables_number   1
_chemical_formula_structural   Li3TbScBe3ZnInGaSbArBNHeC
_chemical_formula_sum
'Li3 Tb1 Sc1 Be3 Zn1 In1 Ga1 Sb1 Ar1 B1 N1 He1 C1'
_cell_volume   10.81482034
_cell_formula_units_Z   1
loop_
 _symmetry_equiv_pos_site_id
 _symmetry_equiv_pos_as_xyz
  1  'x, y, z'
loop_
 _atom_site_type_symbol
 _atom_site_label
 _atom_site_symmetry_multiplicity
 _atom_site_fract_x
 _atom_site_fract_y
 _atom_site_fract_z
 _atom_site_occupancy
  Sc  Sc0  1  0.55882353  0.70980392  0.35686275  1
  Sb  Sb1  1  0.41960784  0.50196078  0.13333333  1
  In  In2  1  0.43725490  0.40588235  0.52156863  1
  Ga  Ga3  1  0.55294118  0.49411765  0.35294118  1
  Tb  Tb4  1  0.22941176  0.49411765  0.43921569  1
  Zn  Zn5  1  0.38627451  0.19411765  0.43333333  1
  Ar  Ar6  1  0.08627451  0.18235294  0.10588235  1
  Be  Be7  1  0.00000000  0.02156863  0.01960784  1
  N  N8  1  0.00392157  0.02156863  0.00980392  1
  Li  Li9  1  0.00588235  0.01568627  0.00196078  1
  B  B10  1  0.00784314  0.01372549  0.01176471  1
  Li  Li11  1  0.00392157  0.01176471  0.00196078  1
  Be  Be12  1  0.00392157  0.01764706  0.00980392  1
  Li  Li13  1  0.00196078  0.00980392  0.00392157  1
  Be  Be14  1  0.00000000  0.02156863  0.00784314  1
  He  He15  1  0.00196078  0.00980392  0.00000000  1
  C  C16  1  0.00784314  0.02352941  0.00588235  1
```
```python
TypeError: 'NoneType' object is not subscriptable
```

**Comment by atztogo** [comment] 2022-10-11 13:00
Could you raise new issue?
https://github.com/spglib/spglib/issues/new/choose
